In [1]:
import torch
randomtensor=torch.rand(3,4,10)
randomtensor



tensor([[[0.5058, 0.1981, 0.1798, 0.2348, 0.7778, 0.7850, 0.4955, 0.4956,
          0.4556, 0.0770],
         [0.5084, 0.1841, 0.8663, 0.8344, 0.6098, 0.9528, 0.6096, 0.1527,
          0.5497, 0.6133],
         [0.0793, 0.9403, 0.7514, 0.0729, 0.3620, 0.4826, 0.7232, 0.5997,
          0.9721, 0.2617],
         [0.2841, 0.7887, 0.9953, 0.4904, 0.0560, 0.5294, 0.7778, 0.3848,
          0.2378, 0.3666]],

        [[0.6102, 0.0365, 0.7219, 0.8461, 0.6863, 0.2657, 0.6534, 0.1825,
          0.1741, 0.5605],
         [0.5030, 0.6430, 0.5626, 0.2603, 0.6914, 0.9438, 0.5782, 0.8067,
          0.8769, 0.8105],
         [0.7845, 0.2532, 0.0398, 0.8202, 0.9995, 0.5831, 0.9892, 0.2335,
          0.3373, 0.7629],
         [0.3957, 0.5218, 0.8153, 0.1642, 0.0400, 0.1746, 0.0830, 0.2835,
          0.8718, 0.3446]],

        [[0.6999, 0.8642, 0.6893, 0.2672, 0.9661, 0.1679, 0.6271, 0.3308,
          0.9655, 0.5354],
         [0.1024, 0.4074, 0.8258, 0.1741, 0.7000, 0.6345, 0.7817, 0.8893,
          0.6

In [2]:
#Create a random tensor with similar shape to an image tensor
image_tensor=torch.rand(size=(3,224,224))
#using size is not necessary
image_tensor.shape,image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [3]:
#tensor of zeroes and ones
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
##Matrix Multiplication
#Two main ways of performing multiplication in neural networks 

In [5]:
#torch.squeeze()=removes all single dimensions from a target tensor
#torch.unsequeeze()=add a single dimension to a target tensor at a specific dim 
#x_unsqueezed=x_unsqueezed(dim=0)
#torch.permute-rearrage the dimensions of a target 

x=torch.randn(2,3,5)
x.size()
torch.permute(x,(2,0,1)).size
x_original=torch.rand(size=(224,224,3))#height,width,color channels
#permute the original tensor 
x_permute=x_original.permute(2,0,1)#shift axis 0->1 1-->2 2-->0
print(f"Previous Shape:{x_original.shape}")
print(f"Original Shape:{x_permute.shape}")


Previous Shape:torch.Size([224, 224, 3])
Original Shape:torch.Size([3, 224, 224])


In [6]:
##Indexing (select data from tensors)
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
x[0][0]

tensor([1, 2, 3])

In [9]:
x[0][0][0]

tensor(1)

In [10]:
x[0][1][0]

tensor(4)

In [11]:
x_original[0,0,0]

tensor(0.4735)

In [12]:
x[0,0,:]

tensor([1, 2, 3])

In [13]:
x[:,:,2]

tensor([[3, 6, 9]])

##Pytorch tensors and Numpy
Numpy is a popular scientific Python numerical computing library
and because of this , Pytorch has functionality to interact with it.
Data in Numpy want in pytorch Tensor -> 'torch.from_numpy(ndarray)'
Pytorch tensor->Numpy ->'torch.tensor.numpy()'

In [14]:
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [15]:
array.dtype

dtype('float64')

In [16]:
torch.arange(1.0,8.0).dtype

torch.float32

In [17]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [18]:
#3Tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [19]:
numpy_tensor.dtype

dtype('float32')

In [20]:
#change the tensor ,what happen to numpy_tensor
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducbility(trying to take random out of random)
In short our neural network learn start with random numberrs->tensor operations->update random numbers to try and makethem
of the data->again->again->again
To reduce the randomness in neural network and pytorch comes the concept of a random seed



In [21]:
torch.rand(3,3)

tensor([[0.9438, 0.6946, 0.8959],
        [0.1375, 0.3904, 0.2595],
        [0.6394, 0.9354, 0.4024]])

In [22]:
#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.5348, 0.6365, 0.6953, 0.8109],
        [0.8583, 0.5075, 0.9031, 0.7686],
        [0.9814, 0.1897, 0.9483, 0.5160]])
tensor([[0.9946, 0.9895, 0.4139, 0.2882],
        [0.5050, 0.7216, 0.1662, 0.8623],
        [0.6686, 0.3691, 0.8023, 0.8057]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [23]:
#Lets make random but reproducable tensor
Random_seed=42
torch.manual_seed(Random_seed)
random_tensor_C=torch.rand(3,4)
# its only work for the one block of code

torch.manual_seed(Random_seed)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [25]:
#Running tensors and pytorchs object on gpu
print("CUDA available: ", torch.cuda.is_available())
print("GPU device name:", torch.cuda.get_device_name(0))

CUDA available:  False


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx